### ISSUE TITLE
MacOS client

### ISSUE THREAD

**Issue by Genxster1998** [mirarr-app/mirarr#15]

**Comment by JermellB** [comment]
These are the steps to build a flutter app on MacOS Enjoy
https://docs.flutter.dev/deployment/macos

**Comment by mirarr-app** [comment]
I'm against releasing without testing. I will either release an alpha version for macos and ipa for ios or find testers first since I don't own those devices myself

**Comment by JermellB** [comment]
I figured, I am much the same. I would have attempted if I owned the devices.

**Comment by mirarr-app** [comment]
@Genxster1998 @JermellB need a macos tester. Let me know if you can test.

**Comment by Genxster1998** [comment]
@JermellB I can but I have only x86_64 Intel device on latest stable macos Sonoma 14.5.
