### ISSUE TITLE
iOS app

### ISSUE THREAD

**Issue by Jazooxd** [mirarr-app/mirarr#16]
Hello Can you plase make it for iOS?

**Comment by JermellB** [comment]
It's open source 
You could try to build the IOS app for yourself.
https://docs.flutter.dev/deployment/ios

**Comment by HuzaifaAzhar** [comment]
Hey I tried building it but I dont have the .env. Could you share it or provide the variables needed?

**Comment by JermellB** [comment]
his code contains this variable, so likely at least that in an .env `final apiKey = dotenv.env['TMDB_API_KEY'];`

**Comment by HuzaifaAzhar** [comment]
yeah i found two different keys being used TMDB API KEY and OMDB API KEY. I built the ipa testing on my phone now

**Comment by HuzaifaAzhar** [comment]
https://github.com/HuzaifaAzhar/mirarr_ios/releases/tag/IPA

**Comment by mirarr-app** [comment]
There will be an official one in the future. If you want to make it yourself build it with github actions so your users know the code is not different with the released one
