### ISSUE TITLE
MissingPlatformDirectoryException

### ISSUE THREAD

**Issue by syswraith** [mirarr-app/mirarr#22]
## Process followed while running the app
1. Downloaded [mirarr.zip](https://github.com/mirarr-app/mirarr/releases/download/9938574431/mirarr.zip)
2. Unzipped in the Downloads folder
3. Given execute permissions using `chmod +x Mirarr`
4. `./Mirarr`

## Console output
```
(Mirarr:3770): Gdk-CRITICAL **: 13:44:25.784: gdk_window_get_state: assertion 'GDK_IS_WINDOW (window)' failed
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: MissingPlatformDirectoryException(Unable to get application documents directory)
#0      getApplicationDocumentsDirectory (package:path_provider/path_provider.dart:122)
<asynchronous suspension>
#1      HiveX.initFlutter (package:hive_flutter/src/hive_extensions.dart:12)
<asynchronous suspension>
#2      main (package:Mirarr/main.dart:14)
<asynchronous suspension>
```

## Window contents
![Screenshot from 2024-07-16 13-47-30](https://github.com/user-attachments/assets/65c38595-f459-4241-bac3-8db72b0184ab)

## System specifications
```
OS: Arch Linux x86_64
Kernel: 6.9.8-zen1-1-zen
Shell: bash 5.2.26
DE: GNOME 46.3.1
Terminal: gnome-terminal
CPU: Intel i3-5005U (4) @ 1.900GHz
```

**Comment by JermellB** [comment]
https://github.com/flutter/gallery/issues/979#issuecomment-1693361972

Try this, there's probably an equivalent for arch.

**Comment by mirarr-app** [comment]
@JermellB is correct. Install xdg-user-dirs on your machine.
