### ISSUE TITLE
Support for content in different languages

### ISSUE THREAD

**Issue by niho9807** [mirarr-app/mirarr#26]
As many people prefer films or series in their own language, it would make sense to add hosters for different languages. These could be marked with a flag, for example (see screenshot).
The hosters or streaming sites are easy to find,
especially on Reddit etc.

![Screenshot_20240716_122212](https://github.com/user-attachments/assets/41576a36-df6b-40b1-8fe3-c041fe255a75)

**Comment by furdiburd** [comment]
This probably won't happen :/
https://github.com/mirarr-app/mirarr/issues/14
Translating the app for other language (German for example) is off the table right now by the dev.

**Comment by niho9807** [comment]
Yeah, saw that in the closed issues too.
Nevertheless, if that would still be an option for Dev, I would be happy to try and make myself useful

**Comment by wonkywolle** [comment]
If possible, fork and integrate the functionality you need. I'm no dart developer but the language is somewhat easy to pick up if you have some knowledge of _a_ programming language.

**Comment by mirarr-app** [comment]
@niho9807 I'll add them If I find reliable providers for them.
