### ISSUE TITLE
An experimental (and maybe ignorant) suggestion for the future built-in video player

### ISSUE THREAD

**Issue by TheD0ct0r101** [mirarr-app/mirarr#33]
Yo, I dont know very much about programming/streaming technicalities, but I had a random thought for an "extra experimental" setting that may or may not improve the watching/immersion experience.

We all get annoyed when a server starts buffering a lot on a free movie site right? Constantly switching servers can become a pain. So, my idea is this;

When the experimental setting is toggled on, it plays the movie/show from multiple servers simultaneously (amount of streams could be configurable depending on the performance of the user's internet) in the background, but only displays one of them. If the player detects that the video timeline is about to run out of buffer space, it would seamlessly switch the displayed stream to whatever streamed server has the most bufferspace accrued. Essentially like turning off/on a layer in photoshop, but in this case its a video stream with it's audio. It _should_ be completely seamless with synced timelines across all the servers and no buffering screen transitions, at the obvious cost of doubling or tripling the stream bandwidth depending on how many servers you decide to use at the same time.

Is this dumb? Is this silly? I'm spitballing here but maybe this sort of thing has already been done before?

**Comment by mirarr-app** [comment]
It's definitely an interesting thought but it requires a lot of hacky workarounds for a feature that I don't think is that much useful. 
But I'm working on a player that does this in somewhat of a similar fashion. In the way that it notices dropped down connections or server hiccups and switches automatically to another one.
