### ISSUE TITLE
An option to select a browser to open links

### ISSUE THREAD

**Issue by androidghosh** [mirarr-app/mirarr#35]
When opening the links, instead of opening it in default webview, it should have a option to open it in any other installed browser. I know android will give this option if you don't select a default browser, but I am talking about a seperate option not connected to android default browser. 

For example, I might use Chrome as my default browser, but it lacks any adblocking so, I might want to use Firefox for mirarr without changing my default browser in android settings everytime.

**Comment by mirarr-app** [comment]
This is a nice suggestion but since I don't want to get the user apps list just for this I don't think I'll add it. But there may be a workaround for Android, if there was I'll add it for Android.
