### ISSUE TITLE
Not showing the watch button

### ISSUE THREAD

**Issue by SupremeMedo** [mirarr-app/mirarr#36]
i logged onto it like 2 hours ago there was a watch button now i re-open it the watch button is not there 
![image](https://github.com/user-attachments/assets/2104c431-b31a-472e-ba77-104dba3cd162)
<bug>

**Comment by mirarr-app** [comment]
I don't allow cam releases. So that movie doesn't have a watch button yet

**Comment by SupremeMedo** [comment]
> I don't allow cam releases. So that movie doesn't have a watch button yet

I mean I went on the same server as the usual and searched it up it was there (Braflix)
