### ISSUE TITLE
[Feature Request] Add in ability to use external BitTorrent client (qBittorrent)

### ISSUE THREAD

**Issue by binhex** [mirarr-app/mirarr#37]
So my feature request is to permit external bittorrent clients to act as the stream server, a good starting point for this would be the popular open source bittorrent client qbittorrent which importantly does support the option for 'Download in sequential order', maybe extending this out to other bittorrent clients that also support sequential order downloads in the future.

**Comment by mirarr-app** [comment]
This is a nice feature to add for sure. Will look into it.

**Comment by binhex** [comment]
Awesome! Thank you, I assume this will be included in the next release, right?
