### ISSUE TITLE
Slow UI on Windows 10

### ISSUE THREAD

**Issue by winddancer** [mirarr-app/mirarr#40]
Very slow UI on Windows 10 - using the latest version.
Loading of the interface along with the movie icons is very slow. User interactions are also slow in showing any response at all. Overall very slow refresh of UI.

**Comment by mirarr-app** [comment]
I'm sorry you didn't have a good experience but since this is most likely a problem on your end, I'll close the issue.
Next time please explain your problem in details and provide some data that can be worked with. Like benchmarking the app on multiple windows desktops and so on.
