### ISSUE TITLE
TMDB Login error

### ISSUE THREAD

**Issue by bachig26** [mirarr-app/mirarr#49]
I'm getting an error `Failed to get account id. Please try again.`.

my login works well when tried along the web browser but it doesn't work in the app. I just tried in the windows version v1.4.3.

@mirarr-app please have look into this issue if this can be fixed.

**Comment by mirarr-app** [comment]
@bachig26 you're correct. Since I proxied all tmdb requests through cloudflare this might be the cause. I'll revert back logging in without proxies.

**Comment by mirarr-app** [comment]
Check latest version
