### ISSUE TITLE
cannot find setup file

### ISSUE THREAD

**Issue by sumedhctrl** [mirarr-app/mirarr#55]
i downloaded the zip and unzipped it but i cant find any setup file pls help

**Comment by mirarr-app** [comment]
> i downloaded the zip and unzipped it but i cant find any setup file pls help

There is no setup file just launch the program

**Comment by mirarr-app** [comment]
@sumedhctrl don't create multiple issues. Launch the Mirarr executable.

**Comment by sumedhctrl** [comment]
how do i launch it? i downloaded the files and i cant find the app

**Comment by mirarr-app** [comment]
> how do i launch it? i downloaded the files and i cant find the app

If you have windows, there's a Mirarr.exe file in the zip you downloaded. Open that.

**Comment by sumedhctrl** [comment]
![image](https://github.com/user-attachments/assets/0a08a257-f7df-480c-b207-bbbe5e20a3a5)
no?

**Comment by mirarr-app** [comment]
> ![image](https://private-user-images.githubusercontent.com/178251350/386252171-0a08a257-f7df-480c-b207-bbbe5e20a3a5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE2MDYxODAsIm5iZiI6MTczMTYwNTg4MCwicGF0aCI6Ii8xNzgyNTEzNTAvMzg2MjUyMTcxLTBhMDhhMjU3LWY3ZGYtNDgwYy1iMjA3LWJiYmU1ZTIwYTNhNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTExNFQxNzM4MDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01ODBjOWQwNTljYmZjMzQyZmFlYTExMjAzMjQ1NjQ5NTk3ZDgzMDAzYjNjYzdmOWU2M2FjODYxNTFlZTdhMjYwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.L2-A1K4yIBRurd82jbk7bbVfbEJs1LiOMnbKvwzTxOA) how do i open the file

you downloaded the wrong zip. this is for linux. download mirarr-windows.zip
