### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by BreadGuy291** [mirarr-app/mirarr#63]
I might look stupid but how do i install this on linux? When i extract the zip file all i see are two folders named "data" and "lib" and an executable file (i think) thats named mirarr

**Comment by mirarr-app** [comment]
@BreadGuy291 hey.
Make sure the Mirarr file is executable.
`chmod +x Mirarr`

Then run it. Either via a gui by double clicking on it or in terminal `./Mirarr`
